CREATE TABLE IF NOT EXISTS Admin (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  pseudo VARCHAR(15) NOT NULL UNIQUE,
  mdp VARCHAR(20) NOT NULL,
  prenom VARCHAR(20) NOT NULL,
  nom VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL,
  PRIMARY KEY (id),
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Admin_temp (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  pseudo VARCHAR(15) NOT NULL UNIQUE,
  mdp VARCHAR(20) NOT NULL,
  prenom VARCHAR(20) NOT NULL,
  nom VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL,
  PRIMARY KEY (id),
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Plat (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  libelle VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  url_image VARCHAR(50),
  comm_chef TEXT,
  prix DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (id),
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Client (
  id_Client SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(30) NOT NULL UNIQUE,
  email VARCHAR(30) NOT NULL,
  telephone VARCHAR(15) NOT NULL,
  PRIMARY KEY (id),
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Reservation (
  id_Resa SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_Client SMALLINT UNSIGNED NOT NULL,
  nbr_Invites SMALLINT UNSIGNED NOT NULL,
  date_Resa DATETIME NOT NULL,
  PRIMARY KEY (id_Resa),
  CONSTRAINT fk_client_id
  REFERENCES Client(id_Client)
)
ENGINE=INNODB;

CREATE TRIGGER after_insert_admin AFTER INSERT
ON Admin FOR EACH ROW
DELETE FROM Admin_temp WHERE pseudo=NEW.pseudo;
